export { scoreCandidates, scoreSingle, rawMetricsFor } from './curviness';
export type { RawMetrics } from './curviness';
export { dedupeCandidates, sameRoad } from './dedupe';
export { pickCandidates, vsFastestLabel } from './rank';
export { gradeHeatSegments } from './gradeHeat';
export type { GradeSegment } from './gradeHeat';
export { buildTags } from './tags';
export { gradeFromRadiusM, isHairpin } from './gradeFromRadius';
export { scoreCorners } from './scoreCorners';
export { shareWhere } from './roadShares';
